config/routes.rb
Rails.application.routes.draw do


  resources :applications
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  #root
  root 'pages#home', as: 'home'

  #pages
  get  'dashboard'=>'pages#dashboard', as: 'user_dashboard'
  
  #users
  devise_for :users,:controllers=>{registrations:'registrations',
                                   sessions:'users/sessions'}

  resources :profiles
  resources :faculties
  resources :hrs

  #jobs
  resources :jobs

  #documents
  resources :documents

  #documentspaces
  resources :document_spaces

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application.rb
class Application < ApplicationRecord
  belongs_to :faculty
  belongs_to :job
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private
  # Overwriting the sign_out redirect path method
  def after_sign_out_path_for(*)
    new_user_session_path
  end

  #def require_login
  #  unless
  #end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :set_application, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /applications
  # GET /applications.json
  def index
    jobs = current_user.hr.jobs
    @applications = Array.new
    jobs.each do |job|
      job_faculties_map = Hash.new
      job_faculties_map[job] = Array.new
      if job.faculties.length > 0
        job.faculties.each do |faculty|
          job_faculties_map[job] << faculty
        end
        @applications << job_faculties_map
      end
    end
    @applications
  end

  # GET /applications/1
  # GET /applications/1.json
  def show
  end

  # GET /applications/new
  def new
    @application = Application.new
  end

  # GET /applications/1/edit
  def edit
  end

  # POST /applications
  # POST /applications.json
  def create

    current_user_id = current_user.id
    @faculty = User.find(current_user_id)
    faculty = current_user.faculty
    job = Job.find(params[:job_id])

    @test = User.find(job.hr.id)

    @third = Job.find(params[:job_id])


    #send mail
    #
    begin
    UserMailer.application_notification(@faculty,@test,@third).deliver
    faculty.jobs << job
    #@application = Application.new(:faculty => faculty, :job => job)
    #@application.save
    #respond_to do |format|
    #if @application.save
    #format.html { redirect_to @application, notice: 'Application was successfully created.' }
    #format.json { render :show, status: :created, location: @application }
    #else
    #format.html { render :new }
    #format.json { render json: @application.errors, status: :unprocessable_entity }
    #end
    #end
    rescue
      faculty.jobs << job
    end

    redirect_back(fallback_location: jobs_path)
  end

  # PATCH/PUT /applications/1
  # PATCH/PUT /applications/1.json
  def update
    respond_to do |format|
      if @application.update(application_params)
        format.html {redirect_to @application, notice: 'Application was successfully updated.'}
        format.json {render :show, status: :ok, location: @application}
      else
        format.html {render :edit}
        format.json {render json: @application.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application.destroy
    respond_to do |format|
      format.html {redirect_to applications_url, notice: 'Application was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_application
    @application = Application.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def application_params
    params.fetch(:application, {}).permit(:job_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def parent_layout(layout)
    @view_flow.set(:layout, output_buffer)
    output = render(:file => "#{layout}")
    self.output_buffer = ActionView::OutputBuffer.new(output)
  end
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/_apply-form.erb
<%= form_tag(applications_path, method: :post) %>
<%= hidden_field_tag('job_id',@job.id) %>
<%= submit_tag "Apply for this Job Now", :class => 'btn btn-common btn-sm' %>
<!--<a href="#" class="btn btn-common btn-sm">Apply for this Job</a>-->

app/views/applications/_form.html.erb
<%= form_with(model: application, local: true) do |form| %>
  <% if application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(application.errors.count, "error") %> prohibited this application from being saved:</h2>

      <ul>
      <% application.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/applications/edit.html.erb
<h1>Editing Application</h1>

<%= render 'form', application: @application %>

<%= link_to 'Show', @application %> |
<%= link_to 'Back', applications_path %>

app/views/applications/index.html.erb
<% content_for :dashboard_content do %>

  <% if @applications.count < 1 %>
    <h1>No Applications</h1>
  <% else %>
    <div class="container">
      <% @applications.each do |application| %>
        <% application.each do |job, employees| %>
          <% employees.each do |employee| %>
            <div class="box col-md-12">
              <div class="row">
                <div class="col-md-1">
                  <p style="margin-bottom: 15px">
                    <b style="font-size: 20px;">#<%= job.id %></b>
                  </p>
                  <a target="_blank" href="#">
                    <span class="ti-envelope" style="font-size: 40px" title="Resume"></span>
                  </a>
                </div>
                <div class="col-md-2">
                  <img src="<%= employee.user.profile.picture %>" height="80" style="border-radius: 8px;"/>
                </div>
                <div class="col-md-5">
                  <b style="font-size: 20px"><%= employee.user.name %></b><br/>
                  Born on
                  <b style="font-size: 15px"><%= employee.user.profile.dob %></b><br/>
                  Lives in <b style="font-size:14px"><%= employee.user.profile.street_address %>,</b><br/>
                  <b style="font-size: 14px"><%= employee.user.profile.city %> City</b><br/>
                  Contact No. <b style="font-size: 14px"><%= employee.user.profile.contact_number %></b>
                </div>
                <div class="col-md-4">
                  <!--                <b style="font-size: 14px">Date Applied:</b><br/>
                                  <b style="font-size: 14px">{{date('F j, Y \a\t g:i a',
                                    strtotime($applicant->pivot->created_at))}}</b><br/>
                                  {{-- <b style="font-size: 12px">{{date('g:i a', strtotime($applicant->pivot->created_at))}}</b>--}}
                                  <br/>-->
                  <a href="<%= profile_path(employee.user) %>"
                     class="btn btn-common btn-block">
                    View User Profile
                  </a>
                </div>
              </div>
              <hr/>
              <p style="font-size:16px;">
                Applied for Job:
                <a href="<%= job_path(job) %>" target="_blank">
                  <b><%= job.title %></b>
                </a>
              </p>
            </div>

          <% end %>
        <% end %>
      <% end %>
    </div>
  <% end %>
<% end %>
<% parent_layout 'pages/dashboard' %>

app/views/applications/new.html.erb
<h1>New Application</h1>

<%= render 'form', application: @application %>

<%= link_to 'Back', applications_path %>

app/views/applications/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_application_path(@application) %> |
<%= link_to 'Back', applications_path %>