config/routes.rb
Rails.application.routes.draw do


  resources :applications
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  #root
  root 'pages#home', as: 'home'

  #pages
  get  'dashboard'=>'pages#dashboard', as: 'user_dashboard'
  
  #users
  devise_for :users,:controllers=>{registrations:'registrations',
                                   sessions:'users/sessions'}

  resources :profiles
  resources :faculties
  resources :hrs

  #jobs
  resources :jobs

  #documents
  resources :documents

  #documentspaces
  resources :document_spaces

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/hr.rb
class Hr < ApplicationRecord
  belongs_to :user
  has_many :jobs

end

app/controllers/hrs_controller.rb
class HrsController < ApplicationController
  before_action :set_hr, only: [:show, :edit, :update, :destroy]

  # GET /hrs
  # GET /hrs.json
  def index
    @hrs = Hr.all
  end

  # GET /hrs/1
  # GET /hrs/1.json
  def show
  end

  # GET /hrs/new
  def new
    @hr = Hr.new
  end

  # GET /hrs/1/edit
  def edit
  end

  # POST /hrs
  # POST /hrs.json
  def create
    @hr = Hr.new(hr_params)

    respond_to do |format|
      if @hr.save
        format.html { redirect_to @hr, notice: 'Hr was successfully created.' }
        format.json { render :show, status: :created, location: @hr }
      else
        format.html { render :new }
        format.json { render json: @hr.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hrs/1
  # PATCH/PUT /hrs/1.json
  def update
    respond_to do |format|
      if @hr.update(hr_params)
        format.html { redirect_to @hr, notice: 'Hr was successfully updated.' }
        format.json { render :show, status: :ok, location: @hr }
      else
        format.html { render :edit }
        format.json { render json: @hr.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hrs/1
  # DELETE /hrs/1.json
  def destroy
    @hr.destroy
    respond_to do |format|
      format.html { redirect_to hrs_url, notice: 'Hr was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hr
      @hr = Hr.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hr_params
      params.fetch(:hr, {})
    end
end

app/helpers/hrs_helper.rb
module HrsHelper
end

app/views/hrs/_form.html.erb
<%= form_with(model: hr, local: true) do |form| %>
  <% if hr.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hr.errors.count, "error") %> prohibited this hr from being saved:</h2>

      <ul>
      <% hr.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/hrs/edit.html.erb
<h1>Editing Hr</h1>

<%= render 'form', hr: @hr %>

<%= link_to 'Show', @hr %> |
<%= link_to 'Back', hrs_path %>

app/views/hrs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hrs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hrs.each do |hr| %>
      <tr>
        <td><%= link_to 'Show', hr %></td>
        <td><%= link_to 'Edit', edit_hr_path(hr) %></td>
        <td><%= link_to 'Destroy', hr, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hr', new_hr_path %>

app/views/hrs/new.html.erb
<h1>New Hr</h1>

<%= render 'form', hr: @hr %>

<%= link_to 'Back', hrs_path %>

app/views/hrs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_hr_path(@hr) %> |
<%= link_to 'Back', hrs_path %>