config/routes.rb
Rails.application.routes.draw do


  resources :applications
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  #root
  root 'pages#home', as: 'home'

  #pages
  get  'dashboard'=>'pages#dashboard', as: 'user_dashboard'
  
  #users
  devise_for :users,:controllers=>{registrations:'registrations',
                                   sessions:'users/sessions'}

  resources :profiles
  resources :faculties
  resources :hrs

  #jobs
  resources :jobs

  #documents
  resources :documents

  #documentspaces
  resources :document_spaces

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application.rb
class Application < ApplicationRecord
  belongs_to :faculty
  belongs_to :job
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :document_space
  mount_uploader :attachment, AttachmentUploader
end

app/models/document_space.rb
class DocumentSpace < ApplicationRecord
  belongs_to :faculty
  has_many :documents
end

app/models/faculty.rb
class Faculty < ApplicationRecord
  belongs_to :user
  has_many :document_spaces
  has_many :applications
  has_many :jobs, :through => :applications
end

app/models/hr.rb
class Hr < ApplicationRecord
  belongs_to :user
  has_many :jobs

end

app/models/job.rb
class Job < ApplicationRecord
  #enum type: [:pt,:ft,:greater_than_20k,:greater_than_30k]

  validates :title, presence: true
  validates :job_type, presence: true
  validates :salary, presence: true
  validates :desc, presence: true

  belongs_to :hr
  has_many :applications
  has_many :faculties, :through => :applications

  scope :job_type, -> (job_type) {where job_type: job_type}
  scope :term, -> (search_term) {where("title like ? or desc like ?", "%#{search_term}%", "%#{search_term}%")}
  scope :salary, -> (expected_salary) {where("salary > ?", "#{expected_salary}")}

  #scope :part_time, -> {where(job_type: "PT")}
  #scope :full_time, -> {where(job_type: "FT")}
  #scope :average, -> {  }

  def self.send_chain(methods)
    methods.inject(self, :send)
  end

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  mount_uploader :picture, AvatarUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :faculty
  has_one :hr
  has_one :profile
end

app/controllers/hrs_controller.rb
class HrsController < ApplicationController
  before_action :set_hr, only: [:show, :edit, :update, :destroy]

  # GET /hrs
  # GET /hrs.json
  def index
    @hrs = Hr.all
  end

  # GET /hrs/1
  # GET /hrs/1.json
  def show
  end

  # GET /hrs/new
  def new
    @hr = Hr.new
  end

  # GET /hrs/1/edit
  def edit
  end

  # POST /hrs
  # POST /hrs.json
  def create
    @hr = Hr.new(hr_params)

    respond_to do |format|
      if @hr.save
        format.html { redirect_to @hr, notice: 'Hr was successfully created.' }
        format.json { render :show, status: :created, location: @hr }
      else
        format.html { render :new }
        format.json { render json: @hr.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hrs/1
  # PATCH/PUT /hrs/1.json
  def update
    respond_to do |format|
      if @hr.update(hr_params)
        format.html { redirect_to @hr, notice: 'Hr was successfully updated.' }
        format.json { render :show, status: :ok, location: @hr }
      else
        format.html { render :edit }
        format.json { render json: @hr.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hrs/1
  # DELETE /hrs/1.json
  def destroy
    @hr.destroy
    respond_to do |format|
      format.html { redirect_to hrs_url, notice: 'Hr was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hr
      @hr = Hr.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hr_params
      params.fetch(:hr, {})
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    #@jobs = Job.all
    @jobs = Job.paginate(:page => params[:page], :per_page => 5).order(updated_at: :desc)

    if search_params[:title] != nil && search_params[:title] != ''
      @jobs = @jobs.term(search_params[:title])
    end
    if search_params[:salary] != nil && search_params[:salary] != ''
      @jobs = @jobs.salary(search_params[:salary])
    end
    if search_params[:job_type] != nil && search_params[:job_type] != ''
      @jobs = @jobs.job_type(search_params[:job_type])
    end


    # Para lang sa search form
    @job = Job.new
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show

  end

  # GET /jobs/new
  def new
    #@job_type=Hash.new("FT"=>"Full-Time","PT"=>"Part-Time")
    if !(current_user.user_type == 'HR')
      redirect_to(jobs_path)
    else
      @job = Job.new
    end
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)
    @job.hr_id = current_user.hr.id
    respond_to do |format|
      if @job.save
        format.html {redirect_to @job, notice: 'Job was successfully created.'}
        format.json {render :show, status: :created, location: @job}
      else
        format.html {render :new}
        format.json {render json: @job.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html {redirect_to @job, notice: 'Job was successfully updated.'}
        format.json {render :show, status: :ok, location: @job}
      else
        format.html {render :edit}
        format.json {render json: @job.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html {redirect_to jobs_url, notice: 'Job was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_job
    @job = Job.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def job_params
    #params.fetch(:job, {})
    params.require(:job).permit(:title, :job_type, :salary, :desc)
  end

  def search_params
    params.fetch(:job, {}).permit(:title, :salary, :job_type)
  end

=begin
  def search_params
    params.require(:job).permit(:title,job_type)
  end
=end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    if user_signed_in?
      redirect_to(user_dashboard_path)
    else
    @jobs=Job.all
    render 'pages/home'
    end
  end

  def dashboard
    if !user_session
      redirect_to(new_user_session_path)
    elsif !current_user.profile
      redirect_to(new_profile_path)
    else
      render 'pages/user/dashboard'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def parent_layout(layout)
    @view_flow.set(:layout, output_buffer)
    output = render(:file => "#{layout}")
    self.output_buffer = ActionView::OutputBuffer.new(output)
  end
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/helpers/hrs_helper.rb
module HrsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/inc/_dashboard-blocks.html.erb
<div class="row">
  <div class="col-md-12">

    <a href="<%= profile_path(current_user) %>">
      <div class="col-md-3 col-sm-3 col-xs-12 f-category">
        <div class="icon">
          <i class="ti-user"></i>
        </div>
        <h3>Profile</h3>
      </div>
    </a>
    <% if current_user.faculty %>
    <a href="<%= document_spaces_path %>">
      <div class="col-md-3 col-sm-3 col-xs-12 f-category">
        <div class="icon">
          <i class="ti-folder"></i>
        </div>
        <h3>My Guru Drive</h3>
      </div>
    </a>
    <% elsif current_user.hr %>
      <a href="<%= applications_path %>">
        <div class="col-md-3 col-sm-3 col-xs-12 f-category">
          <div class="icon">
            <i class="ti-bookmark"></i>
          </div>
          <h3>Applications</h3>
        </div>
      </a>
    <% end %>
    <%= link_to(destroy_user_session_path,method: :delete) do %>
      <div class="col-md-3 col-sm-3 col-xs-12 f-category">
        <div class="icon">
          <i class="ti-filter"></i>
        </div>
        <h3>Log Out</h3>
      </div>
      <% end %>
  </div>
</div>

app/views/inc/_header.html.erb
<div class="page-header" style="background: url('/img/banner1.jpg');">
  <div class="row">
    <div class="col-md-12">
      <div class="breadcrumb-wrapper">
        <h2 class="product-title"><%= yield :current_header %></h2>
      </div>
    </div>
  </div>
</div>

app/views/inc/_jobs.html.erb
<section class="find-job section">
  <div class="container">
    <br/>
  <div class="row">
    <%= form_for @job, method: :get ,  html: { multipart: true } do |form| %>
    <div class="col-md-5">
      <%= form.text_field :title,{placeholder: "Search",:class=>'form-control'} %>
    </div>
      <div class="col-md-3">
        <div class="search-category-container">
      <%= form.select(:job_type,[['Part Time', 'PT'],['Full Time', 'FT']],{include_blank: 'Job Type'},{:class => 'dropdown-product selectpicker'}) %>

        </div>
      </div>

      <div class="col-md-3">
        <div class="search-category-container">
      <%= form.select(:salary,[['20000+ PHP', "20000"], ['30000+ PHP', "30000"]],{include_blank: 'Salary'},{:class=>'dropdown-product selectpicker'}) %>
        </div>
        </div>

      <div class="col-md-1">
      <%= button_tag( :class => "btn btn-primary") do %>
        <i class="fa fa-search" aria-hidden="true"></i>
      <% end %>
      </div>
    <% end %>
  </div>

    <br/>
    <div class="row">
      <h2 class="section-title">Jobs</h2>
      <% if @jobs.any? %>
        <% @jobs.each do |job| %>
          <div class="job-list col-md-12">
            <div class="thumb">
              <a href="<%= job_path(job) %>"><img width="100"
                                                  src="<%= job.hr.user.profile.picture %>" alt=""></a>
            </div>
            <div class="job-list-content">
              <h4><a style="font-size:20px;" href="<%= job_path(job) %>"><%= job.title %></a></h4>
              <p>
                <% if job.job_type == 'FT' %>
                  <span class="full-time">Full-Time</span>
                <% elsif job.job_type == 'PT' %>
                  <span class="part-time">Part-Time</span>
                <% end %>
              </p>
              <p>Posted by<span style="font-weight:bold;color:#FC4A1A;" class="text-primary">&nbsp<%= job.hr.user.name %></span></p>
              <!--
              Posted by <span style="font-weight:bold;color:#FC4A1A"
                              class="text-primary">{{$job->hr->user->name}}</span>
                              -->
              <p><%= job.desc %></p>
              <div class="job-tag">
                <div class="pull-left col-md-9">
                  <div class="meta-tag" style="word-wrap:break-word;">
                    <!--
                  <span><i class="ti-location-pin"></i>{{$job->hr->user->profile->street_address}}
                                                          , {{$job->hr->user->profile->city}}</span>
                                                          -->
                    <span>
                                        <i class="ti-location-pin"></i><%= job.hr.user.profile.street_address %>
                      , <%= job.hr.user.profile.city %>
                                      </span>
                    <span><i class="ti-money"></i><%= job.salary %></span>
                    <br/>
                  </div>
                </div>
                <div class="col-md-3">

                  <a href="<%= job_path(job) %>" class="btn btn-common btn-rm">More Details</a>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <h3>No Jobs Found.</h3>
      <% end %>
    </div>
  </div>
  <div class="center">
  <%= will_paginate @jobs %>
  </div>
</section>

app/views/inc/_navbar.html.erb
<div class="logo-menu">
  <nav class="navbar navbar-default main-navigation" role="navigation" data-spy="affix" data-offset-top="50">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand logo" href="<%= home_path %>"><h3>Instruu</h3></a>
      </div>
      <div class="collapse navbar-collapse" id="navbar">
        <ul class="nav navbar-nav">
          <% if !user_session %>
            <li>
              <a class="<%= yield :active_home %>" href="<%= home_path %>">
                Home
              </a>
            </li>
          <% end %>
          <li>
            <a class="<%= yield :active_jobs %>" href="<%= jobs_path %>">
              Job Listings
            </a>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <% if current_user.user_type == 'HR' %>
              <li class="">
                <a href="<%= new_job_path %>" class="btn btn-common"><i class="ti-pencil-alt"></i>&nbsp;Post A Job</a>
              </li>
            <% end %>
            <li>
              <a href="<%= user_dashboard_path %>">
                <% if current_user.profile %>
                  <% if current_user.profile.picture %>
                <img width="18" class="img-circle" src="<%= current_user.profile.picture %>"/>
                    <% end %>
                <% end %>
                &nbsp;<%= current_user.name %>
                &nbsp<span class="caret"></span></a>
              <ul class="dropdown">
                <li>
                  <a href="<%= user_dashboard_path %>">Dashboard</a>
                </li>
                <li>
                  <%= link_to('Log Out', destroy_user_session_path, method: :delete) %>
                </li>
              </ul>
            </li>
          <% else %>
            <li class="right"><a href="<%= new_user_session_path %>"><i class="ti-lock"></i> Log In</a></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/inc/_school-details.html.erb
<aside>
  <div class="sidebar">
    <h2 class="medium-title">School Details</h2>
    <div class="box">
      <div class="img-thumbnail">
        <img class="img-responsive" src="/img/clients/img1.png" alt="img">
      </div>
      <div class="text-box">
        <h4>{{$job->hr->user->name}}</h4>
        <p>{!! $job->hr->user->profile->description !!}
        </p>
        <strong>Established on</strong>
        <p> {{$date}}</p>
        <strong>Location</strong>
        <p>{{$job->hr->user->profile->street_address}}
          , {{$job->hr->user->profile->city}} </p>
        <strong>Contact No.</strong>
        <p>{{$job->hr->user->profile->contact_number}}</p>
      </div>
    </div>
  </div>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instruu <%= yield :title %></title>
    <%= csrf_meta_tags %>
    <link type="image/x-icon" href="/favicon.ico" rel="icon" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
  <div class="header">
    <%= render 'inc/navbar' %>
    <section id="intro-bg">
      <%= yield :tagline %>
    </section>
  </div>

    <%= yield :content %>

  <footer>
    <div id="copyright">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <p>All Rights reserved &copy; 2017 - Template Designed & Developed by <a rel="nofollow"
                                                                                     href="http://graygrids.com">GrayGrids</a>
            </p>
          </div>
        </div>
      </div>
    </div>
  </footer>
  <a href="#" class="back-to-top">
    <i class="ti-arrow-up"></i>
  </a>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>